[project]
name = "paired-comparisons"
version = "0.1.0"
description = "Blog post on Paired Comparison models in PyMC, Turing.jl, and STAN"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit>=4.6.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
